# code: language=ansible
---
- name: Copy custom GRUB boot image to the target system
  ansible.builtin.copy:
      src: boot_image.png
      dest: "{{ grub_boot_image }}"
      owner: root
      group: root
      mode: '0644'
  become: true

- name: Check if GRUB config exists
  ansible.builtin.stat:
      path: /etc/default/grub
  register: grub_config

- name: Update GRUB config
  ansible.builtin.template:
      src: grub.cfg.j2
      dest: /etc/default/grub
      validate: bash -n %s
      owner: root
      group: root
      mode: '0644'
  when: grub_config.stat.exists

- name: Update GRUB
  ansible.builtin.command:
      cmd: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: grub_config.stat.exists
