---
dependency:
    name: galaxy
driver:
    name: docker
platforms:
    - name: almalinux9
      image: almalinux:9
      pre_build_image: true
provisioner:
    name: ansible
verifier:
    name: ansible
